
CREATE DATABASE IF NOT EXISTS db_ScadaBrother
CHARACTER SET = UTF8MB4 
COLLATE = UTF8MB4_GENERAL_CI;

CREATE TABLE IF NOT EXISTS t_Machine(
	MachineID INT  NOT NULL  PRIMARY KEY AUTO_INCREMENT ,
	MachineNO VARCHAR(50) NOT NULL UNIQUE KEY ,
	MachineName VARCHAR(255) NOT NULL ,
	MachineStype VARCHAR(50) NOT NULL DEFAULT 'Brother-1' ,
	IpAddr VARCHAR(50) NOT NULL ,
	PortNum INT NOT NULL ,
	MachineStatus INT NOT NULL DEFAULT 1 ,
	OrderBy INT DEFAULT 1  
)ENGINE=INNODB  DEFAULT CHARSET=UTF8MB4  COLLATE=UTF8MB4_GENERAL_CI ;

CREATE TABLE IF NOT EXISTS t_scadadata(
	ScadaID BIGINT  NOT NULL PRIMARY KEY AUTO_INCREMENT ,
	MachineID INT  NOT NULL ,
	ScadaNO VARCHAR(255) NOT NULL,
	WkcntrNum INT  NOT NULL ,
	WkcntrCount INT  NOT NULL ,
	LedStatus INT  NOT NULL ,
	ItemString VARCHAR(255) ,
	OtherMsg VARCHAR(255) ,
	CreateTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ,
	UNIQUE KEY(MachineID,ScadaNO),
	FOREIGN KEY (MachineID) REFERENCES t_Machine (MachineID)
)ENGINE=INNODB  DEFAULT CHARSET=UTF8MB4  COLLATE=UTF8MB4_GENERAL_CI ;

---------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------

CREATE DATABASE IF NOT EXISTS db_ScadaFANUC 
CHARACTER SET = UTF8MB4 
COLLATE = UTF8MB4_GENERAL_CI;


CREATE TABLE IF NOT EXISTS t_Machine(
	MachineID INT  NOT NULL  PRIMARY KEY AUTO_INCREMENT ,
	MachineNO VARCHAR(50) NOT NULL UNIQUE KEY ,
	MachineName VARCHAR(255) NOT NULL ,
	MachineStype VARCHAR(50) NOT NULL DEFAULT 'FANUC-1' ,
	IpAddr VARCHAR(50) NOT NULL ,
	PortNum INT NOT NULL ,
	MachineStatus INT NOT NULL DEFAULT 1 ,
	OrderBy INT DEFAULT 1  
)ENGINE=INNODB  DEFAULT CHARSET=UTF8MB4  COLLATE=UTF8MB4_GENERAL_CI ;



CREATE TABLE IF NOT EXISTS t_scadadata(
	ScadaID BIGINT  NOT NULL PRIMARY KEY AUTO_INCREMENT ,
	MachineID INT  NOT NULL ,
	ScadaNO VARCHAR(255) NOT NULL ,
	WkcntrNum INT  NOT NULL ,
	WkcntrCount INT  NOT NULL ,
	LedStatus INT  NOT NULL ,
	ItemString VARCHAR(255) ,
	OtherMsg VARCHAR(255) ,
	CreateTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ,
	UNIQUE KEY(MachineID,ScadaNO),
	FOREIGN KEY (MachineID) REFERENCES t_Machine (MachineID)
)ENGINE=INNODB  DEFAULT CHARSET=UTF8MB4  COLLATE=UTF8MB4_GENERAL_CI ;

-----------------------------------------------------------------------------------
-----------------------------------------------------------------------------------

CREATE DATABASE IF NOT EXISTS db_ScadaSYNTEC
CHARACTER SET = UTF8MB4 
COLLATE = UTF8MB4_GENERAL_CI;


CREATE TABLE IF NOT EXISTS t_Machine(
	MachineID INT  NOT NULL  PRIMARY KEY AUTO_INCREMENT ,
	MachineNO VARCHAR(50) NOT NULL UNIQUE KEY ,
	MachineName VARCHAR(255) NOT NULL ,
	MachineStype VARCHAR(50) NOT NULL DEFAULT 'FANUC-1' ,
	IpAddr VARCHAR(50) NOT NULL ,
	PortNum INT NOT NULL ,
	MachineStatus INT NOT NULL DEFAULT 1 ,
	OrderBy INT DEFAULT 1  
)ENGINE=INNODB  DEFAULT CHARSET=UTF8MB4  COLLATE=UTF8MB4_GENERAL_CI ;



CREATE TABLE IF NOT EXISTS t_scadadata(
	ScadaID BIGINT  NOT NULL PRIMARY KEY AUTO_INCREMENT ,
	MachineID INT  NOT NULL ,
	ScadaNO VARCHAR(255) NOT NULL ,
	WkcntrNum INT  NOT NULL ,
	WkcntrCount INT  NOT NULL ,
	LedStatus INT  NOT NULL ,
	ItemString VARCHAR(255) ,
	OtherMsg VARCHAR(255) ,
	CreateTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ,
	UNIQUE KEY(MachineID,ScadaNO),
	FOREIGN KEY (MachineID) REFERENCES t_Machine (MachineID)
)ENGINE=INNODB  DEFAULT CHARSET=UTF8MB4  COLLATE=UTF8MB4_GENERAL_CI ;

---------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------

ALTER TABLE t_Machine ADD trCount INT;
ALTER TABLE t_Machine ADD tdCount INT;
ALTER TABLE t_Machine ADD colIndex INT;
UPDATE t_machine SET trCount=21,tdCount=8 WHERE 1=1
UPDATE t_machine SET colIndex=MachineID WHERE 1=1








